### ISSUE TITLE
Supported ESP32 boards/modules question

### ISSUE THREAD

**Issue by 4yerba** [bob-g4bby/Bob-Edwards--Forth-Stuff#1]
It's a question really, not an issue.

I have zero experience with the ESP32 but I'd like to try the esp32forth. 

Is there an up to date list of the supported ESP32 boards, publicly acessible and open (for the non-FB user) ?

These boards get updated in a pace I can't seem to be able to track reliably.
If there isn't such a list available yet, maybe here could be a place for it   ?
Thanks,
Maciek

**Comment by bob-g4bby** [comment]
Hi Maciek, Brad Nelson, the author of ESP32forth, lists quite a few ESP32 modules [here](https://esp32forth.appspot.com/[ESP32forth](https://esp32forth.appspot.com/ESP32forth.html).html) hasn't been been updated in a while, so I bet there are many more new ones he hasn't tried - but still it gives plenty of choice. The two devices I own are marked ESP32-WROOM-32, have 38 pins and [look like this one on ebay](https://www.ebay.co.uk/itm/284631356047?hash=item424559d28f:g:kh4AAOSwfH9h9nL~&amdata=enc%3AAQAHAAAA4FTWWdY82%2B31n2jYx%2BHrlhrwCfN8EyDxYFQERW0Llyl%2FfvcgcV8gnU6bsmcwPjoqRnhUDnzOM8AVnk8wsOD5yTc%2FZjQsfu74hwA6WGo4lLWWz9ME4Uw95IPuuiYI%2BWTXRKml1ZrdpJMOYHPk1YlBXQ349Q%2B7CL8%2BCFMMvRcDZB3fuNYYVceSfYOz2JHMVb2jzgQQCTXtqXaxpa%2FM4z7RW5YSECvChz5Vrj%2FuNRfRYhfREmBa66DrCAzFUq%2FrldloKFONVhMgalDQKQEm%2FDdbPGzHhHXMfgB7qEnfPnDbHuSI%7Ctkp%3ABk9SR6zprqv6YA). If you get these, the only thing to watch for is when uploading ESP32forth from the Arduino ide, the BOOT button must be pressed at the start of transferring the data, else the ide complains the transfer failed.

**Comment by 4yerba** [comment]
Hi Bob, thanks for the link, broken but I got to that page all right.
I have a module, exactly [this one](https://www.mouser.co.uk/ProductDetail/Espressif-Systems/ESP32-S2-WROVER-IM22S2H3216UH3Q0?qs=vHuUswq2%252BszxnrhiZVBtvw%3D%3D) I bought in 2020. The datasheet  says it's a single core but looks to be supported. Will see.
The Arduino framework and IDE  looks scarry to me but I will force myself this one time.
